-- DROP TABLE Tutor;
-- CREATE TABLE Tutor 
-- (
--     ID int IDENTITY(1,1), 
--     [Email] varchar(max), 
--     [Password] varchar(max), 
--     [User_Name] varchar(max), 
--     [Description] varchar(max), 
--     [Qualification] varchar(max), 
--     [Profile Picture] varchar(max), 
--     [Full Name] varchar(max), 
--     [Contact Number] varchar(max), 
--     [Rating] varchar(max),
--     [Enabled] varchar(max)
-- );
SELECT * FROM Accounts;